#use this to override the namespace other than the helm release
namespace: ""

orbital:
  persistRemoteCallResponses: true
  image:
    repository: orbitalhq/orbital
    tag: "latest"
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistrKeySecretName

  service:
    enabled: true
    type: NodePort
    servicePort: 9022
    containerPort: 9022
    # Set a nodePort which is available if service type is NodePort
    # nodePort: 32080

  podLabels: {}
  replicaCount: 1
  readinessProbe:
    httpGet:
      path: "/api/actuator/health"
      port: 9022
      scheme: HTTP
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: "/api/actuator/health"
      port: 9022
      scheme: HTTP
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

postgresql:
  enabled: true
  auth:
    username: orbital
    database: orbital
    password: orbital
