apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orbital.fullname" . }}-services-config
data:
  services.conf: |-
    services {
      analytics-server {
          rsocket="tcp://vyne-analytics-server:7654"
          url="http://orbital-query-analytics"
      }
      orbital-server {
          rsocket="tcp://orbital.{{ .Release.Namespace }}.svc.cluster.local:7655"
          url="http://orbital.{{ .Release.Namespace }}.svc.cluster.local:9022"
      }
      stream-server {
          url="http://orbital-stream-server"
      }
    }
