apiVersion: v1
kind: ConfigMap
metadata:
  name: orbital-config
data:
  services.conf: |-
    services {
        "schema-server": {
            "rsocket-port": "{{ .Values.schema.service.rsocket.containerPort }}",
            "url": "http://schema-server.{{ .Values.schema.namespace }}.svc.cluster.local:{{ .Values.schema.service.http.containerPort }}"
        }
    }
  roles.conf: |-
    defaultUserRoleMappings {
      roles = [ "Viewer" ]
    }
        
    defaultApiClientRoleMappings {
      roles = [ "QueryRunner" ]
    }
        
    grantedAuthorityMappings {
      Admin {
        grantedAuthorities = [  
          "RunQuery",
          "CancelQuery",
          "ViewQueryHistory",
          "ViewHistoricQueryResults",
          "BrowseCatalog",
          "BrowseSchema",
          "EditSchema",
          "ViewCaskDefinitions",
          "EditCaskDefinitions",
          "ViewPipelines",
          "EditPipelines",
          "ViewAuthenticationTokens",
          "EditAuthenticationTokens",
          "ViewConnections",
          "EditConnections",
          "ViewUsers",
          "EditUsers"
        ]
    }
        
    Viewer {
      grantedAuthorities = [ "BrowseCatalog" ]
    }
        
    QueryRunner {
      grantedAuthorities = [ "RunQuery" ]
    }
        
    PlatformManager {
      grantedAuthorities = [  
        "CancelQuery",
        "ViewQueryHistory",
        "ViewHistoricQueryResults",
        "BrowseSchema",
        "EditSchema",
        "ViewCaskDefinitions",
        "EditCaskDefinitions",
        "ViewPipelines",
        "EditPipelines",
        "ViewAuthenticationTokens",
        "EditAuthenticationTokens",
        "ViewConnections",
        "EditConnections"
        ]
      }
    }
