{{- if not (empty $.Values.streamServer.secretConfig) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orbital.fullname" . }}-env-stream-server
  labels: {{- include "streamServer.metaLabels" . | nindent 4 }}
data:
  {{- range $key, $value := $.Values.streamServer.config }}
  {{ $key }}: {{ $value | squote }}
  {{- end }}
{{- end }}
