apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orbital.fullname" . }}-config
data:
  {{- if and (.Values.orbital.workspace.enabled) (not (empty .Values.orbital.workspace.config)) }}
  workspaces.conf: |
    {{ .Values.orbital.workspace.config | nindent 4 }}
  {{- end}}
  {{- if .Values.orbital.project.enabled }}
  taxi.conf: |
    {{ .Values.orbital.project.config | nindent 4 }}
  {{- end }}
  roles.conf: |-
    defaultUserRoleMappings {
      roles = [ "Viewer" ]
    }
        
    defaultApiClientRoleMappings {
      roles = [ "QueryRunner" ]
    }
        
    grantedAuthorityMappings {
      Admin {
        grantedAuthorities = [  
          "RunQuery",
          "CancelQuery",
          "ViewQueryHistory",
          "ViewHistoricQueryResults",
          "BrowseCatalog",
          "BrowseSchema",
          "EditSchema",
          "ViewCaskDefinitions",
          "EditCaskDefinitions",
          "ViewPipelines",
          "EditPipelines",
          "ViewAuthenticationTokens",
          "EditAuthenticationTokens",
          "ViewConnections",
          "EditConnections",
          "ViewUsers",
          "EditUsers"
        ]
    }
        
    Viewer {
      grantedAuthorities = [ "BrowseCatalog" ]
    }
        
    QueryRunner {
      grantedAuthorities = [ "RunQuery" ]
    }
        
    PlatformManager {
      grantedAuthorities = [  
        "CancelQuery",
        "ViewQueryHistory",
        "ViewHistoricQueryResults",
        "BrowseSchema",
        "EditSchema",
        "ViewCaskDefinitions",
        "EditCaskDefinitions",
        "ViewPipelines",
        "EditPipelines",
        "ViewAuthenticationTokens",
        "EditAuthenticationTokens",
        "ViewConnections",
        "EditConnections"
        ]
      }
    }
