---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbital
  namespace: {{ .Values.orbital.namespace }}
  labels:
    {{- include "orbital.metaLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.orbital.replicaCount }}
  selector:
    matchLabels:
      {{- include "orbital.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
       {{- include "orbital.metaLabels" . | nindent 8 }}
       {{- if .Values.orbital.podLabels }}
       {{ toYaml .Values.orbital.podLabels | nindent 8 }}
       {{- end }}
    spec:
      {{- if .Values.orbital.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.orbital.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: "orbital"
        image: {{ .Values.orbital.image.repository }}:{{ .Values.orbital.image.tag }}
        imagePullPolicy: {{ .Values.orbital.image.pullPolicy }}
        env:
        - name: OPTIONS
          value: >-
            --vyne.analytics.mode=InProcess
            --vyne.analytics.persistRemoteCallResponses=true
            --vyne.analytics.persistResults=true
        volumeMounts:
          - name: orbital-config
            mountPath: /opt/service/config
        ports:
        - name: orbital
          containerPort: {{ .Values.orbital.service.containerPort }}
          protocol: TCP
        readinessProbe:
{{ toYaml .Values.orbital.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.orbital.livenessProbe | indent 10 }}
      volumes:
        - name: orbital-config
          configMap:
            name: orbital-config
