---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "orbital.fullname" . }}
  namespace: {{ template "orbital.namespace" . }}
  labels:
    {{- include "orbital.metaLabels" . | nindent 4 }}
  {{- if .Values.orbital.deploymentAnnotations }}
  annotations:
  {{- range $key, $value := .Values.orbital.deploymentAnnotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  {{- if not .Values.orbital.autoscaling.enabled }}
  replicas: {{ .Values.orbital.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orbital.selectorLabels" . | nindent 6 }}
  {{- if .Values.orbital.updateStrategy }}
  strategy:
  {{ toYaml .Values.orbital.updateStrategy | indent 4 }}
  {{ - end }}
  { { - if .Values.orbital.deploymentMinReadySeconds } }
  minReadySeconds: { { .Values.orbital.deploymentMinReadySeconds } }
  { { - end } }

  template:
    metadata:
      annotations:
        {{- if .Values.orbital.podAnnotations }}
        {{- range $key, $value := .Values.orbital.podAnnotations }}
        {{ $key }}: { { $value | quote }}
        {{- end }}
        {{- end }}
      labels:
       {{- include "orbital.metaLabels" . | nindent 8 }}
       {{- if .Values.orbital.podLabels }}
       {{ toYaml .Values.orbital.podLabels | nindent 8 }}
       {{- end }}
    spec:
      {{- if or .Values.orbital.serviceAccount.create .Values.orbital.serviceAccount.name }}
      serviceAccountName: {{ template "orbital.serviceAccountName" . }}
      {{- end }}
      {{- if (and (or .Values.orbital.serviceAccount.create .Values.orbital.serviceAccount.name) .Values.orbital.serviceAccount.automountServiceAccountToken) }}
      automountServiceAccountToken: true
      {{- else }}
      automountServiceAccountToken: false
      {{ end }}
      {{- if .Values.orbital.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.orbital.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.orbital.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- if .Values.orbital.priorityClassName }}
      priorityClassName: "{{ .Values.orbital.priorityClassName }}"
      {{- end }}
      {{- if .Values.orbital.hostAliases }}
      hostAliases:
        {{- toYaml .Values.orbital.hostAliases | nindent 6 }}
      {{- end }}
      {{- if .Values.orbital.dnsPolicy }}
      dnsPolicy: { { .Values.orbital.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.orbital.dnsConfig }}
      dnsConfig:
      {{ toYaml .Values.orbital.dnsConfig | indent 8 }}
      {{- end }}
      containers:
      - name: "orbital"
        image: {{ .Values.orbital.image.repository }}:{{ .Values.orbital.image.tag }}
        imagePullPolicy: {{ .Values.orbital.image.pullPolicy }}
        securityContext:
        {{ toYaml .Values.orbital.containerSecurityContext | nindent 10 }}
        env:
        - name: OPTIONS
          value: >-
            --vyne.analytics.persistRemoteCallResponses={{ .Values.orbital.persistRemoteCallResponses }}
            --vyne.db.username=orbital
            --vyne.db.password=orbital
            --vyne.db.host={{ .Release.Name }}-postgresql.{{ template "orbital.namespace" . }}.svc.cluster.local
            --vyne.services.config-file=/opt/service/config/services/services.conf
            {{- if .Values.orbital.security.enabled }}
            --vyne.security.openIdp.enabled=true
            --vyne.security.openIdp.jwks-uri={{ .Values.orbital.security.jwksUri }}
            --vyne.security.openIdp.issuerUrl={{ .Values.orbital.security.issuerUrl }}
            --vyne.security.openIdp.clientId={{ .Values.orbital.security.clientId }}
            --vyne.security.openIdp.scope={{ .Values.orbital.security.scope }}
            --vyne.security.openIdp.require-https={{ .Values.orbital.security.requireHttps }}
            {{- end }}
            {{- if .Values.orbital.project.enabled }}
            --vyne.workspace.project-file={{ .Values.orbital.project.path }}
            {{- else }}
            --vyne.workspace.config-file={{ .Values.orbital.workspace.path }}
            {{- end }}
        - name: JAVA_OPTS
          value: >-
            -Xms256m
            -Xmx1024m
        {{- if .Values.orbital.lifecycle }}
        lifecycle:
        {{- toYaml .Values.orbital.lifecycle | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: orbital-config
            mountPath: /opt/service/config
          - name: orbital-services-config
            mountPath: /opt/service/config/services
        ports:
        - name: orbital
          containerPort: {{ .Values.orbital.service.containerPort }}
          {{- if .Values.orbital.service.hostPort }}
          hostPort: { { .Values.orbital.service.hostPort }}
          {{ - end }}
          protocol: TCP
        readinessProbe:
        {{ toYaml .Values.orbital.readinessProbe | indent 10 }}
        livenessProbe:
        {{ toYaml .Values.orbital.livenessProbe | indent 10 }}
        {{- if .Values.orbital.resources }}
        resources:
        {{ toYaml .Values.orbital.resources | indent 10 }}
        {{- end }}
      securityContext:
      {{ toYaml .Values.orbital.podsecuritycontext | nindent 8 }}
      volumes:
        - name: orbital-config
          configMap:
            name: orbital-config
        - name: orbital-services-config
          configMap:
            name: orbital-services-config
          {{ - if (and (not .Values.orbital.serviceAccount.automountServiceAccountToken) (or .Values.orbital.serviceAccount.create .Values.orbital.serviceAccount.name)) }}
        - name: {{ template "orbital.serviceAccountTokenName" . }}
          secret:
            secretName: {{ template "orbital.serviceAccountTokenName" . }}
            items:
              - key: token
                path: token
              - key: ca.crt
                path: ca.crt
              - key: namespace
                path: namespace
          {{- end }}
