---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbital-stream-server
  namespace: {{ template "orbital.namespace" . }}
  labels:
    {{- include "streamServer.metaLabels" . | nindent 4 }}
  {{- if .Values.streamServer.deploymentAnnotations }}
  annotations:
  {{ - range $key, $value := .Values.streamServer.deploymentAnnotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  {{- if not .Values.streamServer.autoscaling.enabled }}
  replicas: {{ .Values.streamServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "streamServer.selectorLabels" . | nindent 6 }}
  {{- if .Values.streamServer.updateStrategy }}
  strategy:
  {{ toYaml .Values.streamServer.updateStrategy | indent 4 }}
  {{- end } }
  {{- if .Values.streamServer.deploymentMinReadySeconds }}
  minReadySeconds: {{ .Values.streamServer.deploymentMinReadySeconds }}
  {{- end }}

  template:
    metadata:
      annotations:
        {{- if .Values.orbital.podAnnotations }}
        {{- range $key, $value := .Values.orbital.podAnnotations }}
        {{ $key }}: { { $value | quote }}
        {{- end }}
        {{- end }}
      labels:
       {{- include "streamServer.metaLabels" . | nindent 8 }}
       {{- if .Values.streamServer.podLabels }}
       {{ toYaml .Values.streamServer.podLabels | nindent 8 }}
       {{- end }}
    spec:
      {{- if .Values.streamServer.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.streamServer.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: "orbital"
        image: {{ .Values.streamServer.image.repository }}:{{ .Values.streamServer.image.tag }}
        imagePullPolicy: {{ .Values.streamServer.image.pullPolicy }}
        securityContext:
        {{ toYaml .Values.streamServer.containerSecurityContext | nindent 10 }}
        env:
        - name: OPTIONS
          value: >-
            --vyne.services.config-file=/opt/service/config/services/services.conf
        - name: JAVA_OPTS
          value: >-
            -Xms256m
            -Xmx1024m
        {{- if .Values.streamServer.lifecycle }}
        lifecycle:
        {{- toYaml .Values.streamServer.lifecycle | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: orbital-services-config
            mountPath: /opt/service/config/services
        ports:
        - name: stream-server
          containerPort: {{ .Values.streamServer.service.containerPort }}
          {{- if .Values.streamServer.service.hostPort }}
          hostPort: {{ .Values.streamServer.service.hostPort }}
          {{- end }}
          protocol: TCP
        readinessProbe:
        {{ toYaml .Values.streamServer.readinessProbe | indent 10 }}
        livenessProbe:
        {{ toYaml .Values.streamServer.livenessProbe | indent 10 }}
        {{- if .Values.streamServer.resources }}
        resources:
        {{ toYaml .Values.streamServer.resources | indent 10 }}
        {{- end }}
      {{- if .Values.streamServer.affinity }}
      affinity:
      {{ toYaml .Values.streamServer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.streamServer.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{ toYaml .Values.streamServer.topologySpreadConstraints | indent 8 }}
      {{- end }}
      securityContext:
      {{ toYaml .Values.streamServer.podsecuritycontext | nindent 8 }}
      {{ - if .Values.streamServer.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.streamServer.nodeSelector | indent 8 }}
      {{ - end } }
      terminationGracePeriodSeconds: {{ .Values.streamServer.terminationGracePeriodSeconds }}
      {{ - if .Values.streamServer.tolerations }}
      tolerations:
      {{ toYaml .Values.streamServer.tolerations | indent 8 }}
      {{ - end }}
      volumes:
        - name: orbital-services-config
          configMap:
            name: orbital-services-config
