---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbital-stream-server
  namespace: {{ template "orbital.namespace" . }}
  labels: {{- include "streamServer.metaLabels" . | nindent 4 }}
  {{- if not (empty .Values.streamServer.deploymentAnnotations) }}
  annotations:
  {{- range $key, $value := .Values.streamServer.deploymentAnnotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  {{- if not .Values.streamServer.autoscaling.enabled }}
  replicas: {{ .Values.streamServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "streamServer.selectorLabels" . | nindent 6 }}
  {{- if not (empty .Values.streamServer.updateStrategy) }}
  strategy: {{- toYaml .Values.streamServer.updateStrategy | nindent 4 }}
  {{- end }}
  {{- if .Values.streamServer.deploymentMinReadySeconds }}
  minReadySeconds: {{ .Values.streamServer.deploymentMinReadySeconds }}
  {{- end }}
  template:
    metadata:
      {{ if not (empty .Values.orbital.podAnnotations) }}
      annotations:
        {{- if .Values.orbital.podAnnotations }}
        {{- range $key, $value := .Values.orbital.podAnnotations }}
        {{ $key }}: { { $value | quote }}
        {{- end }}
        {{- end }}
      {{- end }}
      labels: {{- include "streamServer.metaLabels" . | nindent 8 }}
       {{- if not (empty .Values.streamServer.podLabels) }}
         {{- toYaml .Values.streamServer.podLabels | nindent 8 }}
       {{- end }}
    spec:
      {{- if .Values.streamServer.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.streamServer.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: "orbital"
        image: {{ .Values.streamServer.image.repository }}:{{ .Values.streamServer.image.tag }}
        imagePullPolicy: {{ .Values.streamServer.image.pullPolicy }}
        {{ if not (empty .Values.streamServer.containerSecurityContext) }}
        securityContext: {{- toYaml .Values.streamServer.containerSecurityContext | nindent 10 }}
        {{- end }}
        env:
        - name: OPTIONS
          value: >-
            --vyne.services.config-file=/opt/service/config/services/services.conf
        - name: JAVA_OPTS
          value: >-
            -Xms256m
            -Xmx1024m
        {{- if .Values.streamServer.lifecycle }}
        lifecycle: {{- toYaml .Values.streamServer.lifecycle | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: orbital-services-config
            mountPath: /opt/service/config/services
        ports:
        - name: stream-server
          containerPort: {{ .Values.streamServer.service.containerPort }}
          {{- if .Values.streamServer.service.hostPort }}
          hostPort: {{ .Values.streamServer.service.hostPort }}
          {{- end }}
          protocol: TCP
        readinessProbe: {{- toYaml .Values.streamServer.readinessProbe | nindent 10 }}
        livenessProbe: {{- toYaml .Values.streamServer.livenessProbe | nindent 10 }}
        {{- if .Values.streamServer.startupProbe }}
        startupProbe: {{- toYaml .Values.streamServer.startupProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.streamServer.resources }}
        resources: {{- toYaml .Values.streamServer.resources | nindent 10 }}
        {{- end }}
      {{- if .Values.streamServer.affinity }}
      affinity: {{- toYaml .Values.streamServer.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.streamServer.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml .Values.streamServer.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{ if not (empty .Values.streamServer.securityContext) }}
      securityContext: {{- toYaml .Values.streamServer.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.streamServer.nodeSelector }}
      nodeSelector: {{- toYaml .Values.streamServer.nodeSelector | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.streamServer.terminationGracePeriodSeconds }}
      {{- if .Values.streamServer.tolerations }}
      tolerations: {{- toYaml .Values.streamServer.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: orbital-services-config
          configMap:
            name: orbital-services-config
