{{- if .Values.orbital.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "orbital.fullname" . }}
  labels: {{- include "orbital.metaLabels" . | nindent 4 }}
  {{- if .Values.orbital.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.orbital.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.orbital.ingress.ingressClassName }}
  ingressClassName: {{ .Values.orbital.ingress.ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .Values.orbital.ingress.hostname | quote }}
    http:
      paths:
        - backend:
            service:
              name: {{ template "orbital.fullname" . }}
              port:
                number: {{ .Values.orbital.service.servicePort }}
          path: {{ .Values.orbital.ingress.path }}
          pathType: {{ .Values.orbital.ingress.pathType }}
{{- end -}}
