{{- if not (empty $.Values.streamServer.secretConfig) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orbital.fullname" . }}-env-stream-server
  labels: {{- include "streamServer.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := $.Values.streamServer.secretConfig }}
  {{ $k }}: {{ $v | toString | b64enc }}
  {{- end }}
{{- end }}
