---
{{- $supplemental := omit $.Values.orbital.service.supplemental "type" "ports" "selector" "loadBalancerIP" "loadBalancerSourceRanges" "loadBalancerClass" "externalTrafficPolicy" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "orbital.fullname" . }}
  namespace: {{ template "orbital.namespace" . }}
  labels: {{- include "orbital.selectorLabels" . | nindent 4 }}
  {{- with $.Values.orbital.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.orbital.service.type }}
  {{- if (eq .Values.orbital.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.orbital.service.loadBalancerIP }}
  loadBalancerSourceRanges: {{- toYaml .Values.orbital.service.loadBalancerSourceRanges | nindent 4 }}
  loadBalancerClass: {{ .Values.orbital.service.loadBalancerClass }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.orbital.service.externalTrafficPolicy }}
  ports:
    - name: orbital-svc
      port: {{ .Values.orbital.service.servicePort }}
      targetPort: {{ .Values.orbital.service.containerPort }}
      appProtocol: http
      protocol: TCP
      {{- if (and (or (eq .Values.orbital.service.type "LoadBalancer") (eq .Values.orbital.service.type "NodePort")) (not (empty .Values.orbital.service.nodePort))) }}
      nodePort: {{ .Values.orbital.service.nodePort }}
      {{- end }}
    - name: rsocket-tcp
      port: 7655
      targetPort: 7655
      appProtocol: tcp
      protocol: TCP
  selector: {{- include "orbital.selectorLabels" . | nindent 4 }}

{{- if $supplemental }}
  {{- toYaml $supplemental | nindent 2 }}
{{- end }}
