{{- if .Values.orbital.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "orbital.serviceAccountName" . }}
  {{- if .Values.orbital.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.orbital.serviceAccount.annotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels: {{- include "orbital.metaLabels" . | nindent 4 }}
 {{- end -}}
